# Generated by Django 6.0.7 on 2026-08-01 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RSVPResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Имя и фамилия')),
                ('attendance', models.CharField(choices=[('yes', 'Обязательно буду!'), ('no', 'К сожалению, не смогу')], max_length=20, verbose_name='Присутствие')),
                ('drinks', models.TextField(blank=True, help_text='Выбранные напитки через запятую', verbose_name='Напитки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата заполнения')),
            ],
            options={
                'verbose_name': 'Ответ гостя',
                'verbose_name_plural': 'Ответы гостей',
                'ordering': ['-created_at'],
            },
        ),
    ]
